parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shared\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Presentation/Api/{Request,Response}/'
            - '../../Presentation/Web/{Request,Response}/'
            - '../../Presentation/Console/{Input,Output}/'
            - '../../Application/**/*Command.php'
            - '../../Application/**/*Query.php'
            - '../../Application/{Exception}/'
            - '../../Infrastructure/Outbox/Command/OutboxMessageEnvelope.php'
            - '../../Infrastructure/RateLimiting/{Configuration,Exception,Attribute,Dto}/'
            - '../../Infrastructure/RateLimiting/RateLimiter.php'
            - '../../Infrastructure/Outbox/{ValueObject}/'
            - '../../DomainModel/{Dto,Event,Enum,Entity,Specification,Exception,ValueObject}/'
            - '../../**/Tests/'
        tags: [ 'controller.service_arguments' ]

    query.bus.adapter:
        class: Shared\Infrastructure\MessageBus\SymfonyMessageBus
        arguments:
            $messageBus: '@query.bus'

    event.bus.adapter:
        class: Shared\Infrastructure\MessageBus\SymfonyMessageBus
        arguments:
            $messageBus: '@event.bus'

    command.bus.adapter:
        class: Shared\Infrastructure\MessageBus\SymfonyMessageBus
        arguments:
            $messageBus: '@command.bus'

    # Services
    Shared\Application\Service\ApplicationService:
        arguments:
            $commandBus: '@command.bus.adapter'
            $queryBus: '@query.bus.adapter'
            $logger: '@logger'

    #############################################################################
    # HTTP Client
    #############################################################################
    Shared\Infrastructure\HttpClient\HttpClientLoggingMiddleware:
        arguments:
            $logger: '@logger'

    Shared\Infrastructure\HttpClient\HttpClientLoggingMiddlewareFactory:
        arguments:
            $middleware: '@Shared\Infrastructure\HttpClient\HttpClientLoggingMiddleware'

    guzzle.middleware.logging:
        class: Closure
        factory: ['@Shared\Infrastructure\HttpClient\HttpClientLoggingMiddlewareFactory', 'create']

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
            $config:
                handler: '@guzzle.handler'

    guzzle.handler:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        calls:
            - [push, ['@guzzle.middleware.logging']]

    Psr\Http\Client\ClientInterface: '@GuzzleHttp\Client'

    #############################################################################
    # Global Assert Validation Error Handler
    #############################################################################
    Shared\Infrastructure\ErrorHandler\GlobalErrorHandler:
        tags:
            - { name: kernel.event_subscriber }

    #############################################################################
    # Responder
    #############################################################################
    Shared\Presentation\Responder\JsonResponder:
        tags:
            - { name: kernel.event_subscriber }

    Shared\Presentation\Responder\HtmlResponder:
        tags:
            - { name: kernel.event_subscriber }
            
    Shared\Presentation\Responder\ConsoleResponder: ~

    #############################################################################
    # Rate limits
    #############################################################################
    Shared\Infrastructure\RateLimiting\Storage\CacheRateLimitStorage:
        arguments:
            $cache: '@rate_limiting.cache'
            $logger: '@logger'

    Shared\Infrastructure\RateLimiting\Storage\RateLimitStorageInterface:
        alias: Shared\Infrastructure\RateLimiting\Storage\CacheRateLimitStorage

    Shared\Infrastructure\RateLimiting\Strategy\FixedWindowStrategy:
        arguments:
            $storage: '@Shared\Infrastructure\RateLimiting\Storage\RateLimitStorageInterface'

    Shared\Infrastructure\RateLimiting\Identifier\IpIdentifier: ~

    Shared\Infrastructure\RateLimiting\Identifier\RequestIdentifierInterface:
        alias: Shared\Infrastructure\RateLimiting\Identifier\IpIdentifier

    Shared\Infrastructure\RateLimiting\RateLimiterFactory:
        arguments:
            $storage: '@Shared\Infrastructure\RateLimiting\Storage\RateLimitStorageInterface'

    Shared\Infrastructure\RateLimiting\EventListener\RateLimitListener:
        arguments:
            $rateLimiterFactory: '@Shared\Infrastructure\RateLimiting\RateLimiterFactory'
            $identifier: '@Shared\Infrastructure\RateLimiting\Identifier\RequestIdentifierInterface'
            $logger: '@logger'
        tags:
            - { name: kernel.event_subscriber }

    #############################################################################
    # Outbox
    #############################################################################
    Shared\Infrastructure\Outbox\Repository\OutboxEventRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    Shared\Infrastructure\Outbox\Service\OutboxEventProcessor:
        arguments:
            $eventBus: '@event.bus.adapter'

    Shared\Infrastructure\Outbox\Command\OutboxMessageEnvelopeHandler:
        arguments:
            $eventBus: '@event.bus.adapter'
        tags:
            - { name: 'messenger.message_handler', bus: 'event.bus' }

    #############################################################################
    # Event Store
    #############################################################################
    Shared\Infrastructure\EventStore\Repository\DoctrineEventStore:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    Shared\DomainModel\Service\EventStoreInterface:
        class: Shared\Infrastructure\EventStore\Repository\DoctrineEventStore