parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shared\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Presentation/Api/{Request,Response}/'
            - '../../Presentation/Web/{Request,Response}/'
            - '../../Presentation/Console/{Input,Output}/'
            - '../../Application/**/*Command.php'
            - '../../Application/**/*Query.php'
            - '../../Application/{Exception}/'
            - '../../DomainModel/{Dto,Event,Enum,Entity,Exception,ValueObject}/'
            - '../../**/Tests/'
        tags: [ 'controller.service_arguments' ]

    # HTTP Client Logging Middleware
    Shared\Infrastructure\HttpClient\HttpClientLoggingMiddleware:
        arguments:
            $logger: '@logger'

    Shared\Infrastructure\HttpClient\HttpClientLoggingMiddlewareFactory:
        arguments:
            $middleware: '@Shared\Infrastructure\HttpClient\HttpClientLoggingMiddleware'

    guzzle.middleware.logging:
        class: Closure
        factory: ['@Shared\Infrastructure\HttpClient\HttpClientLoggingMiddlewareFactory', 'create']

    # Define the HTTP client service
    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
            $config:
                handler: '@guzzle.handler'

    guzzle.handler:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        calls:
            - [push, ['@guzzle.middleware.logging']]

    Psr\Http\Client\ClientInterface: '@GuzzleHttp\Client'

    # Global Assert Validation Error Handler
    Shared\Infrastructure\ErrorHandler\GlobalErrorHandler:
        tags:
            - { name: kernel.event_subscriber }

    # Responder
    Shared\Presentation\Responder\JsonResponder:
        tags:
            - { name: kernel.event_subscriber }

    Shared\Presentation\Responder\HtmlResponder:
        tags:
            - { name: kernel.event_subscriber }
            
    Shared\Presentation\Responder\ConsoleResponder: ~
