doctrine:
    orm:
        mappings:
            Domain2:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain2/DomainModel/Model'
                prefix: 'App\Domain2\DomainModel\Model'
                alias: Domain2