parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain2\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../DomainModel/Model/'
        tags: ['controller.service_arguments']