image: php:8.3-cli

cache:
  paths:
    - vendor/

before_script:
  # Install system dependencies
  - apt-get update && apt-get install -y git zip unzip
  # Install Composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  # Install project dependencies
  - cd code && composer install --no-interaction --no-progress

stages:
  - build
  - quality
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cd code && composer install --no-interaction --no-progress
    - echo "Compile complete."

php-cs-fixer:
  stage: quality
  script:
    - echo "Running PHP CS Fixer..."
    - vendor/bin/php-cs-fixer fix -v --using-cache=no --config=../tools/.php-cs-fixer.php
  allow_failure: false

deptrac:
  stage: quality
  script:
    - echo "Running Deptrac..."
    - vendor/bin/deptrac analyse --config-file=../tools/deptrac/deptrac-domain.yaml --no-cache | grep -v 'Uncovered'
    - vendor/bin/deptrac analyse --config-file=../tools/deptrac/deptrac-layers.yaml --no-cache | grep -v 'Uncovered'

phpstan:
  stage: quality
  script:
    - echo "Running PHPStan..."
    - vendor/bin/phpstan analyse src --configuration=../tools/phpstan.neon

psalm:
  stage: quality
  script:
    - echo "Running Psalm..."
    - vendor/bin/psalm --config=../tools/psalm.xml --no-cache

phpunit:
  stage: quality
  script:
    - echo "Running PHPUnit tests..."
    - vendor/bin/phpunit -c ../tools/phpunit.xml.dist

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
