parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CoreDomain\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Presentation/Api/{Request,Response}/'
            - '../../Presentation/Web/{Request,Response}/'
            - '../../Presentation/Console/{Input,Output}/'
            - '../../Application/**/*Command.php'
            - '../../Application/**/*Query.php'
            - '../../Application/**/*Dto.php'
            - '../../Application/**/*Exception.php'
            - '../../DomainModel/{Dto,Event,Enum,Model,Entity,Specification,Exception,ValueObject}/'
            - '../../**/Tests/'
        tags: [ 'controller.service_arguments' ]