services:
    web:
        build:
            context: containers/nginx
        container_name: es-web
        ports:
            - "${NGINX_HTTP_PORT}:80"
            - "${NGINX_HTTPS_PORT}:443"
        volumes:
            - ../code:/var/www/html/code
            - ./containers/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./containers/nginx/ssl:/etc/nginx/ssl
        links:
            - php
        networks:
            - es-network
    php:
        build:
            context: containers/php
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        image: es-php
        container_name: es-php
        ports:
            - "${PHP_PORT}:9000"
        volumes:
            - ../code:/var/www/html/code
            - ../tools:/var/www/html/tools
            - ./containers/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - es-network
    postgres:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        container_name: es-postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        volumes:
            - ./data/postgres_data:/var/lib/postgresql/data:rw
            - ./containers/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        networks:
            - es-network

networks:
    es-network:
        external: true
        driver: bridge

volumes:
    database_data:
