openapi: 3.0.0
info:
  title: 'Enterprise Skeleton API'
  version: 1.0.0
paths:
  /api/test:
    get:
      tags:
        - Test
      summary: 'Test route message'
      operationId: 59e85abadf91b5a4c7be04a5b9563d3e
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
              example: Test
tags:
  -
    name: Test
    description: Test
