openapi: 3.0.0
info:
  title: 'Enterprise Skeleton API'
  version: 1.0.0
paths:
  /api/test:
    get:
      tags:
        - Test
      summary: 'Test route message'
      operationId: 16498ca3e9817be324bb26ee12ed22c0
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
              example: Test
tags:
  -
    name: Test
    description: Test
