monolog:
    channels:
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [404, 405]
            grouped:
                type: group
                members: [streamed, logstash]
            streamed:
                type: stream
                path: "php://stdout"
                level: debug
                formatter: monolog.formatter.json
            logstash:
                type: socket
                connection_string: 'tcp://logstash:50000'
                level: debug
                formatter: monolog.formatter.json
                handler: nested
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: stream
                path: "php://stdout"
                level: debug
                formatter: monolog.formatter.json
            errors:
                type: stream
                path: "php://stderr"
                level: error
                formatter: monolog.formatter.json

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [404, 405]
            grouped:
                type: group
                members: [streamed, logstash]
            streamed:
                type: stream
                path: "php://stdout"
                level: info
                formatter: monolog.formatter.json
            logstash:
                type: socket
                connection_string: 'tcp://logstash:50000'
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
                formatter: monolog.formatter.json
