services:
  redis-sentry:
    image: redis:alpine
    profiles: ["sentry"]
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-sentry-data:/data
    networks:
      - es-network

  postgres-sentry:
    image: postgres:9.6-alpine
    profiles: ["sentry"]
    command: postgres -c 'max_connections=200'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-sentry-data:/var/lib/postgresql/data
    networks:
      - es-network

  sentry-init:
    image: sentry:9.1.2
    platform: linux/amd64
    profiles: ["sentry"]
    depends_on:
      redis-sentry:
        condition: service_healthy
      postgres-sentry:
        condition: service_healthy
    command: "sentry upgrade --noinput"
    environment:
      SENTRY_SECRET_KEY: "v5j*b^*z1f6469^hfx8jrlvsg27(tj%1qbsb^8cj_48*1(hz1h"
      SENTRY_POSTGRES_HOST: postgres-sentry
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_DB_NAME: postgres
      SENTRY_REDIS_HOST: redis-sentry
      SENTRY_REDIS_PORT: 6379
      SENTRY_MAIL_HOST: ""
      SENTRY_SINGLE_ORGANIZATION: "true"
      SENTRY_FEATURES: "organizations:create"
    networks:
      - es-network

  sentry-create-user:
    image: sentry:9.1.2
    platform: linux/amd64
    profiles: ["sentry"]
    depends_on:
      - sentry-init
    command: >
      bash -c "sentry createuser
      --email admin@example.com
      --password admin123
      --superuser
      --no-input"
    environment:
      SENTRY_SECRET_KEY: "v5j*b^*z1f6469^hfx8jrlvsg27(tj%1qbsb^8cj_48*1(hz1h"
      SENTRY_POSTGRES_HOST: postgres-sentry
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_DB_NAME: postgres
      SENTRY_REDIS_HOST: redis-sentry
      SENTRY_REDIS_PORT: 6379
      SENTRY_MAIL_HOST: ""
      SENTRY_SINGLE_ORGANIZATION: "true"
      SENTRY_FEATURES: "organizations:create"
    networks:
      - es-network

  sentry:
    image: sentry:9.1.2
    platform: linux/amd64
    profiles: ["sentry"]
    depends_on:
      redis-sentry:
        condition: service_healthy
      postgres-sentry:
        condition: service_healthy
      sentry-init:
        condition: service_completed_successfully
      sentry-create-user:
        condition: service_completed_successfully
    ports:
      - "9001:9000"
    volumes:
      - './sentry-data:/var/lib/sentry/files'
    environment:
      SENTRY_SECRET_KEY: "v5j*b^*z1f6469^hfx8jrlvsg27(tj%1qbsb^8cj_48*1(hz1h"
      SENTRY_POSTGRES_HOST: postgres-sentry
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_DB_NAME: postgres
      SENTRY_REDIS_HOST: redis-sentry
      SENTRY_REDIS_PORT: 6379
      SENTRY_MAIL_HOST: ""
      SENTRY_SINGLE_ORGANIZATION: "true"
      SENTRY_FEATURES: "organizations:create"
    networks:
      - es-network

  sentry-cron:
    image: sentry:9.1.2
    platform: linux/amd64
    profiles: ["sentry"]
    depends_on:
      - sentry
    command: "sentry run cron"
    volumes:
      - './sentry-data:/var/lib/sentry/files'
    environment:
      SENTRY_SECRET_KEY: "v5j*b^*z1f6469^hfx8jrlvsg27(tj%1qbsb^8cj_48*1(hz1h"
      SENTRY_POSTGRES_HOST: postgres-sentry
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_DB_NAME: postgres
      SENTRY_REDIS_HOST: redis-sentry
      SENTRY_REDIS_PORT: 6379
      SENTRY_MAIL_HOST: ""
      SENTRY_SINGLE_ORGANIZATION: "true"
      SENTRY_FEATURES: "organizations:create"
    networks:
      - es-network

  sentry-worker:
    image: sentry:9.1.2
    platform: linux/amd64
    profiles: ["sentry"]
    depends_on:
      - sentry
    command: "sentry run worker"
    volumes:
      - './sentry-data:/var/lib/sentry/files'
    environment:
      SENTRY_SECRET_KEY: "v5j*b^*z1f6469^hfx8jrlvsg27(tj%1qbsb^8cj_48*1(hz1h"
      SENTRY_POSTGRES_HOST: postgres-sentry
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_DB_NAME: postgres
      SENTRY_REDIS_HOST: redis-sentry
      SENTRY_REDIS_PORT: 6379
      SENTRY_MAIL_HOST: ""
      SENTRY_SINGLE_ORGANIZATION: "true"
      SENTRY_FEATURES: "organizations:create"
    networks:
      - es-network

volumes:
  redis-sentry-data:
  postgres-sentry-data:
  sentry-data:

networks:
  es-network:
    external: true
